# Generated by Django 5.2.4 on 2025-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='hidden_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
