# Generated by Django 5.2.4 on 2025-08-09 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_hidden_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteVisibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_invite', models.CharField(choices=[('store', 'Store'), ('lien', 'Lien externe')], default='store', max_length=10)),
                ('ciblage_type', models.CharField(choices=[('all', 'Tous les utilisateurs'), ('country', 'Par pays'), ('city', 'Par ville')], default='all', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='invites_images')),
                ('url_redirection', models.URLField(blank=True, null=True)),
                ('nombre_invites', models.PositiveIntegerField()),
                ('visites_restantes', models.PositiveIntegerField(default=0)),
                ('unite_visite', models.DecimalField(decimal_places=4, default=0.001, max_digits=6)),
                ('montant_total', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('temps_minimum', models.PositiveIntegerField(default=60)),
                ('cibler_tout_user', models.BooleanField(default=False)),
                ('compteur_visites', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites_lancees', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_visibilite', to='core.store')),
                ('utilisateurs_ayant_visite', models.ManyToManyField(blank=True, related_name='invites_visitees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisiteMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gain_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visite_money', to=settings.AUTH_USER_MODEL)),
                ('visited_stores', models.ManyToManyField(blank=True, to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='InviteVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='core.invitevisibilite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('invite', 'user')},
            },
        ),
    ]
