# Generated by Django 5.2.4 on 2025-08-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitevisibilite_visitemoney_invitevisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitemoney',
            name='visited_links',
            field=models.ManyToManyField(blank=True, to='core.invitevisibilite'),
        ),
    ]
