# Generated by Django 5.2.4 on 2025-08-09 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_visitemoney_visited_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetraitMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(max_length=150)),
                ('numero_beneficiaire', models.CharField(help_text='Numéro Mobile Money ou compte bancaire bénéficiaire', max_length=50)),
                ('nom_compte_beneficiaire', models.CharField(help_text='Nom du compte Mobile Money ou bancaire', max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_retrait', models.DateTimeField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('est_traite', models.BooleanField(default=False)),
                ('message_admin', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits_mobile_money', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
