# Generated by Django 5.2.4 on 2025-08-10 08:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_withdrawalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniteVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=4, default=0.002, max_digits=10, verbose_name='Montant par visite (en USD)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Unité de visite',
                'verbose_name_plural': 'Unités de visite',
            },
        ),
        migrations.CreateModel(
            name='InviteVisibilitePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('transaction_id', models.CharField(max_length=255)),
                ('numero_telephone', models.CharField(max_length=15)),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_valide', models.BooleanField(default=False)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invitevisibilite')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unite_visite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.unitevisite')),
            ],
            options={
                'verbose_name': "Paiement d'invitation",
                'verbose_name_plural': "Paiements d'invitations",
            },
        ),
    ]
