# Generated by Django 5.2.4 on 2025-08-10 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_unitevisite_invitevisibilitepayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitevisite',
            options={},
        ),
        migrations.AlterField(
            model_name='unitevisite',
            name='montant',
            field=models.DecimalField(decimal_places=4, default=0.002, max_digits=10),
        ),
    ]
