# Generated by Django 5.2.4 on 2025-08-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_unitevisite_options_alter_unitevisite_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitevisibilite',
            name='utilisateurs_ayant_visite',
        ),
    ]
