# Generated by Django 5.2.4 on 2025-08-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_invitevisibilite_utilisateurs_ayant_visite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitevisibilite',
            name='ciblage_type',
        ),
    ]
