# Generated by Django 5.2.4 on 2025-08-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_invitevisibilite_ciblage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitevisibilite',
            name='ciblage_type',
            field=models.CharField(choices=[('all', 'Tous les utilisateurs'), ('country', 'Par pays'), ('city', 'Par ville')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
