# Generated by Django 5.2.4 on 2025-08-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_invitevisibilite_ciblage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitevisibilite',
            name='ciblage_type',
            field=models.CharField(blank=True, choices=[('all', 'Tous les utilisateurs'), ('country', 'Par pays'), ('city', 'Par ville')], max_length=10),
        ),
    ]
