from django.urls import path
from .views import user_stores
from core.views import search_store_api
from .views import (
    SignupAPIView,
    UserProfileAPIView,
    UpdateProfileAPIView,
    LogoutAPIView,
    ChangePasswordAPIView,
    MyTokenObtainPairView,
    CreateStoreAPIView,
    ToggleSubscriptionAPIView,
    AddOrUpdateSpotPubAPIView,
    CreateNotificationAPIView,
    ContactStoreAPIView,
    CreateProductAPIView,
    UserStoreListAPIView,
    TypestoreListAPIView,
    TypeBusinessListAPIView,
    CountryListAPIView,
    CityListAPIView,
    StoreUpdateAPIView,
    StoreDeleteAPIView,
    StoreDetailAPIView,
    StoreTestimonialsAPIView,
    CreateTestimonialAPIView,
    SpotPubListAPIView,
    SpotPubStoreDetailAPIView,
    StoreVisitAPIView,
    StoreContactListAPIView,
    CreateStoreNotificationAPIView,
    UserNotificationListAPIView,
    MarkNotificationAsReadAPIView,
    TypeProductListCreateAPIView,
    ProductCreateAPIView,
    ProductDetailAPIView,
    UploadProductPhotoAPIView,
    StoreOwnerProductListAPIView,
    DeleteProductPhotoAPIView,
    CategoryCreateAPIView,
    CategoryListAPIView,
    AssignerCategoryAPIView,
    CategoryDeleteAPIView,
    ProductWithoutCategoryAPIView,
    StoreProductsAPIView,
    AllProductsAPIView,
    ContactProductAPIView,
    StoreContactProductListAPIView,
    CreateTestimonialProductAPIView, 
    ProductTestimonialsListAPIView,
    CartDetailAPIView,
    AddToCartAPIView,
    UpdateCartItemAPIView,
    RemoveFromCartAPIView,
    MobileMoneyPaymentCreateAPIView,
    UserOrderListAPIView,
    UserPointsAPIView,
    StoreSalesHistoryAPIView,
    OrdersByDateAPIView,
    OrderDetailAPIView,
    download_order_invoice_word,
    NumeroPayeByUserCountryAPIView,
    AddStoreCoManagerAPIView,
    CoManagedStoresAPIView,
    RemoveCoManagerAPIView,
    SearchUsersAPIView,
    StoreCoManagerListAPIView,
    LotteryParticipationCreateAPIView,
    LotteryListAPIView,
    LotteryResultAPIView,
    LotteryDrawAPIView,
    ProductPointsListAPIView,
    ProductPointsDetailAPIView,
    PurchaseProductAPIView,
    MyPurchaseListAPIView,
    AdvertisementListAPIView, 
    AdvertisementCreateAPIView,
    PhotoAdsCreateAPIView,
    PhotoAdsByAdListAPIView,
    AdInteractionCreateAPIView,
    CommentCreateAPIView,
    CommentListByAdAPIView,
    HideNotificationAPIView,
    PopUpAdvertisementListAPIView,
    FeaturedStoreListAPIView,
    StoreByTypestoreAPIView,
    StoreByCountryAPIView,
    StoreByCityAPIView,
    StoreByTypeBusinessAPIView,
    store_list_by_city_or_all,
    ProductByCountryAPIView,
    ProductByCityAPIView,
    ProductsGroupedByTypeByCityAPIView,
    SmartStoreListAPIView,
    StoreByTypeBusinessListAPIView
)
from rest_framework_simplejwt.views import (
    TokenRefreshView,
    
)

urlpatterns = [
    path('signup/', SignupAPIView.as_view(), name='signup'),
    path('api/token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', UserProfileAPIView.as_view(), name='profile'),
    path('profile/update/', UpdateProfileAPIView.as_view(), name='profile-update'),
    path('change-password/', ChangePasswordAPIView.as_view(), name='change-password'),
    path('logout/', LogoutAPIView.as_view(), name='logout'),
    path('stores/create/', CreateStoreAPIView.as_view(), name='create-store'),
    path('stores/<int:pk>/toggle-subscription/', ToggleSubscriptionAPIView.as_view(), name='toggle-subscription'),
    path('api/stores/<int:store_id>/spotpub/', AddOrUpdateSpotPubAPIView.as_view(), name='add-update-spotpub'),
    path('stores/<slug:slug>/notify/', CreateNotificationAPIView.as_view(), name='store-notify'),
    path('api/stores/<int:pk>/contact/', ContactStoreAPIView.as_view(), name='contact-store'),
    path('stores/<slug:slug>/products/create/', CreateProductAPIView.as_view(), name='api-create-product'),
    path('stores/user/<int:user_id>/', user_stores, name='user-stores'),
    path('api/stores/user/<int:user_id>/', UserStoreListAPIView.as_view(), name='user-stores'),
    path('api/typestores/', TypestoreListAPIView.as_view(), name='api-typestores'),
    path('api/typebusinesses/', TypeBusinessListAPIView.as_view(), name='api-typebusinesses'),
    path('api/countries/', CountryListAPIView.as_view(), name='api-countries'),
    path('api/cities/', CityListAPIView.as_view(), name='api-cities'),
    path('stores/update/<int:pk>/', StoreUpdateAPIView.as_view(), name='store-update'),
    path('stores/delete/<int:pk>/', StoreDeleteAPIView.as_view(), name='store-delete'),
    path('api/store/<int:pk>/', StoreDetailAPIView.as_view(), name='api-store-detail'),
    path('api/stores/<int:store_id>/testimonials/', StoreTestimonialsAPIView.as_view(), name='store-testimonials'),
    path('api/stores/<int:store_id>/testimonials/', CreateTestimonialAPIView.as_view(), name='create-testimonial'),
    path('api/spotpubs/', SpotPubListAPIView.as_view(), name='spotpub-list'),
    path('api/stores/<int:store_id>/spotpub/view/', AddOrUpdateSpotPubAPIView.as_view(), name='spotpub-detail'),
    path("api/stores/<int:store_id>/spotpub-view/", SpotPubStoreDetailAPIView.as_view()),
    path('api/stores/<int:store_id>/visit/', StoreVisitAPIView.as_view(), name='store-visit'),
    path("api/stores/<int:store_id>/contacts/", StoreContactListAPIView.as_view()),
    path("api/stores/<int:store_id>/notify/", CreateStoreNotificationAPIView.as_view(), name="create-store-notification"),
    path('api/notifications/', UserNotificationListAPIView.as_view(), name='user-notification-list'),
    path('api/notifications/<int:notif_id>/read/', MarkNotificationAsReadAPIView.as_view(), name='mark_notification_read'),
    path('api/type-products/', TypeProductListCreateAPIView.as_view(), name='type-product-list'),
    path('api/products/create/', ProductCreateAPIView.as_view(), name='product-create'),
    path('api/products/<int:pk>/', ProductDetailAPIView.as_view(), name='product-detail'),
    path('api/products/<int:product_id>/photos/', UploadProductPhotoAPIView.as_view(), name='upload_product_photo'),
    path('api/my-products/', StoreOwnerProductListAPIView.as_view(), name='my_products'),
    path('api/photos/<int:pk>/', DeleteProductPhotoAPIView.as_view(), name='delete_photo'),
    path('api/stores/<int:store_id>/categories/create/', CategoryCreateAPIView.as_view(), name='category-create'),
    path('api/stores/<int:store_id>/categories/', CategoryListAPIView.as_view(), name='category-list'),
    path('api/products/<int:product_id>/assign-category/', AssignerCategoryAPIView.as_view(), name='assign-category'),
    path('api/categories/<int:pk>/delete/', CategoryDeleteAPIView.as_view(), name='category-delete'),
    path('api/stores/<int:store_id>/products/without-category/', ProductWithoutCategoryAPIView.as_view()),
    path('api/stores/<int:store_id>/products/', StoreProductsAPIView.as_view(), name='store_products'),
    path('api/products/all/', AllProductsAPIView.as_view(), name='all_products'),
    path('api/products/<int:product_id>/contact/', ContactProductAPIView.as_view(), name='contact_product'),
    path('api/stores/<int:store_id>/contact-products/', StoreContactProductListAPIView.as_view(), name='store_contact_products'),
    path('api/products/<int:product_id>/testimonials/', ProductTestimonialsListAPIView.as_view(), name='product_testimonial_list'),
    path('api/products/testimonials/create/', CreateTestimonialProductAPIView.as_view(), name='product_testimonial_create'),
    path('api/cart/', CartDetailAPIView.as_view(), name='cart_detail'),
    path('api/cart/add/<int:product_id>/', AddToCartAPIView.as_view(), name='cart_add'),
    path('api/cart/update/<int:cart_item_id>/', UpdateCartItemAPIView.as_view(), name='cart_update'),
    path('api/cart/remove/<int:cart_item_id>/', RemoveFromCartAPIView.as_view(), name='cart_remove'),
    path('api/mobile-money/', MobileMoneyPaymentCreateAPIView.as_view(), name='mobile_money_payment'),
    path('api/orders/', UserOrderListAPIView.as_view(), name='user_orders'),
    path('api/user-points/', UserPointsAPIView.as_view(), name='user_points'),
    path('api/stores/<int:store_id>/sales-history/', StoreSalesHistoryAPIView.as_view(), name='store_sales_history'),
    path('api/stores/<int:store_id>/orders-by-date/', OrdersByDateAPIView.as_view(), name='orders-by-date'),
    path('api/orders/<int:pk>/', OrderDetailAPIView.as_view(), name='order-detail'),
    path('api/orders/<int:pk>/download-invoice-word/', download_order_invoice_word, name='download-invoice-word'),
    path('api/numero-paye-by-user/', NumeroPayeByUserCountryAPIView.as_view(), name='numero-paye-user'),
    path('api/stores/<int:store_id>/co-managers/add/', AddStoreCoManagerAPIView.as_view(), name='add-co-manager'),
    path('api/my-co-managed-stores/', CoManagedStoresAPIView.as_view(), name='co-managed-stores'),
    path('api/stores/<int:store_id>/co-managers/remove/', RemoveCoManagerAPIView.as_view(), name='store-remove-co-manager'),
    path('api/search-users/', SearchUsersAPIView.as_view(), name='search-users'),
    path('api/stores/<int:store_id>/co-managers/', StoreCoManagerListAPIView.as_view(), name='store-co-managers'),
    path('api/lotteries/<int:lottery_id>/participate/', LotteryParticipationCreateAPIView.as_view(), name='lottery_participate'),
    path('api/lotteries/', LotteryListAPIView.as_view(), name='lottery_list_api'),
    path('api/lotteries/<int:lottery_id>/result/', LotteryResultAPIView.as_view(), name='lottery-result'),
    path('api/lotteries/<int:lottery_id>/draw/', LotteryDrawAPIView.as_view(), name='lottery_draw'),
    path('api/product-points/', ProductPointsListAPIView.as_view(), name='product_points_list'),
    path('api/product-points/<int:pk>/', ProductPointsDetailAPIView.as_view(), name='product_points_detail'),
    path('api/product-points/<int:pk>/purchase/', PurchaseProductAPIView.as_view(), name='product_points_purchase'),
    path('api/my-purchases/', MyPurchaseListAPIView.as_view(), name='my_purchases_api'),
    path('api/ads/', AdvertisementListAPIView.as_view(), name='advertisement_list'),
    path('advertisements/create/', AdvertisementCreateAPIView.as_view(), name='advertisement-create'),
    path('photo-ads/create/', PhotoAdsCreateAPIView.as_view(), name='photo-ads-create'),
    path('api/search-stores/', search_store_api, name='search_stores_api'),
    path('photo-ads/by-ad/<int:ad_id>/', PhotoAdsByAdListAPIView.as_view(), name='photo-ads-by-ad'),
    path('api/ad-interactions/', AdInteractionCreateAPIView.as_view(), name='ad_interaction_create'),
    path('api/comments/', CommentCreateAPIView.as_view(), name='comment_create'),
    path('api/comments/by-ad/<int:ad_id>/', CommentListByAdAPIView.as_view(), name='comments-by-ad'),
    path('api/notifications/<int:notif_id>/hide/', HideNotificationAPIView.as_view(), name='notification-hide'),
    path('api/popup-ads/', PopUpAdvertisementListAPIView.as_view(), name='popup_ads_list'),
    path('api/featured-stores/', FeaturedStoreListAPIView.as_view(), name='featured_store_list'),
    path('api/stores/by-typestore/<int:typestore_id>/',  StoreByTypestoreAPIView.as_view(), name='stores_by_typestore'),
    path('api/stores/by-country/<int:country_id>/', StoreByCountryAPIView.as_view(), name='api-stores-by-country'),
    path('api/stores/by-city/<int:city_id>/', StoreByCityAPIView.as_view(), name='stores-by-city'),
    path('api/stores/by-typebusiness/', StoreByTypeBusinessAPIView.as_view(), name='stores-by-typebusiness'),
    path('api/stores/by-city-or-all/', store_list_by_city_or_all, name='store-list-by-city-or-all'),
    path('api/products/by-country/<int:country_id>/', ProductByCountryAPIView.as_view(), name='products-by-country'),
    path('api/categories/', CategoryListAPIView.as_view(), name='category-list'),
    path('api/products/by-city/<int:city_id>/', ProductByCityAPIView.as_view(), name='products-by-city'),
    path('api/type-products/', TypeProductListCreateAPIView.as_view(), name='type-product-list'),
    path('api/products/by-city/<int:city_id>/grouped-by-type/', ProductsGroupedByTypeByCityAPIView.as_view()),
    path('api/smart-stores/', SmartStoreListAPIView.as_view(), name='smart_store_list'),
    path('api/stores/', StoreByTypeBusinessListAPIView.as_view(), name='api-stores-by-typebusiness'),
    
    

    

]
