# Generated by Django 5.2.4 on 2025-07-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('commune', models.CharField(help_text='Entrez la commune manuellement', max_length=100)),
                ('description', models.TextField()),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('hotel', 'Hôtel'), ('guesthouse', 'Guesthouse'), ('boutique', 'Boutique'), ('parcelle vide', 'Parcelle vide'), ('terrain agricole', 'Terrain agricole'), ('bureau', 'Bureau'), ('autres', 'Autres')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField(default=False)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/requests/')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/responses/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
