# Generated by Django 5.2.4 on 2025-10-20 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_requete_city_requete_country_response_requete_and_more'),
        ('core', '0014_customuser_latitude_customuser_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Immobusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('commune', models.CharField(help_text='Entrez la commune manuellement', max_length=100)),
                ('description', models.TextField()),
                ('objectif', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', max_length=20)),
                ('type_bien', models.CharField(choices=[('maison', 'Maison'), ('appartement', 'Appartement'), ('hotel', 'Hôtel'), ('guesthouse', 'Guesthouse'), ('boutique', 'Boutique'), ('parcelle vide', 'Parcelle vide'), ('terrain agricole', 'Terrain agricole'), ('bureau', 'Bureau'), ('autres', 'Autres')], max_length=50)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='immobusiness/main_images/')),
                ('actif', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immobusinesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImmobusinessGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='immobusiness/gallery/')),
                ('immobusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='base.immobusiness')),
            ],
        ),
        migrations.CreateModel(
            name='ImmobusinessResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('post_nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/immobusiness_responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('immobusiness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='base.immobusiness')),
            ],
        ),
    ]
