# Generated by Django 5.2.4 on 2025-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_immobusiness_immobusinessgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobusiness',
            name='devise',
            field=models.CharField(blank=True, help_text='Exemple : USD, CDF, EUR', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='immobusiness',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Entrez le prix du bien', max_digits=12, null=True),
        ),
    ]
